account/urls.py
from django.urls import path

from account.views import ProfileView

app_name = 'account'

urlpatterns = [
    path('', ProfileView.as_view(), name='profile'),
]

apps/account/urls.py
from django.urls import path

from apps.account import views

app_name = 'account'

urlpatterns = [
    path('athlete', views.AthleteView.as_view(), name='athlete'),
    path('logout', views.LogOutView.as_view(), name='logout'),
]

stramate/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('grappelli/', include('grappelli.urls')),
    path('admin/', admin.site.urls),
    path('auth/', include('social_django.urls', namespace='social')),

    path('account/', include('apps.account.urls')),
    path('activity/', include('apps.activity.urls')),
    path('', include('apps.page.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

theme/templates/_footer.html
<footer class="relative inset-x-0 bottom-0 my-4 text-xs text-center opacity-50">
    <a href="https://github.com/manhtai/stramate">StraMate</a> &copy; {% now "Y" %}
</footer>

theme/templates/_header.html
{% load heroicons %}

<header class="w-full text-sm text-white bg-gray-900">
<nav class="container flex flex-wrap items-center justify-between p-2 mx-auto" x-data="{ open: false }">
    <div class="relative flex justify-between w-full md:w-auto md:static md:block md:justify-start" x-cloak>
    <nav class="flex items-center mr-8 md:hidden">
        <a href="/" class="text-link">
            {% heroicon_outline "home" class="w-4 h-4 mr-1" %}
            <p class="font-medium">StraMate</p>
        </a>
    </nav>
    <button
        class="block text-xl leading-none bg-transparent border border-transparent border-solid rounded outline-none cursor-pointer md:hidden focus:outline-none"
        type="button"
        @click="open = !open"
        @click.outside="open = false"
    >
        <span x-show="!open">
        {% heroicon_outline "menu" class="w-6 h-6" %}
        </span>
        <span x-show="open">
        {% heroicon_outline "x" class="w-6 h-6" %}
        </span>
    </button>
    </div>

    <div
    class="flex flex-col items-start justify-start flex-grow md:items-center md:flex-row md:justify-between md:flex md:bg-transparent md:my-0 md:space-y-0 md:border-none"
    :class="{ 'block my-2 space-y-3 border-t': open, 'hidden': !open }"
    x-cloak
    >
    <nav class="items-center hidden mr-8 md:flex">
        <a href="/" class="text-link">
            {% heroicon_outline "home" class="w-4 h-4 mr-1" %}
            <p class="font-medium"/>StraMate</p>
        </a>
    </nav>
    <nav class="flex flex-col items-start justify-end opacity-70 md:flex-row md:space-x-4 md:items-center md:space-y-0 space-y-3 " x-cloak>
        {% if user.is_authenticated %}
        <a href="{% url "account:athlete" %}" class="text-link" title="Athlete configuration">
            {% heroicon_outline "cog" class="w-4 h-4 mr-1" %}
            Settings
        </a>
        <a href="{% url "account:logout" %}" class="text-link" title="Log out">
            {% heroicon_outline "logout" class="w-4 h-4 mr-1" %}
            Log out
        </a>
        {% else %}
        <a href="{% url "social:begin" "strava" %}" class="text-link" title="Log out">
            {% heroicon_outline "login" class="w-4 h-4 mr-1" %}
            Sign in
        </a>
        {% endif %}
    </nav>
    </div>
</nav>
</header>

theme/templates/base.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}StraMate{% endblock %}</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <link rel="icon" href="{% static "img/s64.png" %}" />
        <link rel="apple-touch-icon" href="{% static "img/s192.png" %}" />

        <meta name="description" content="A self-hosted data analyzer for your activities">
        <meta property="og:image" content="{% block image %}{% endblock %}" />

        {% tailwind_css %}
        <script src="//unpkg.com/alpinejs" defer></script>
    </head>

    <body class="text-sm text-gray-600 bg-gray-50">
        {% include "_header.html" %}

        {% block before_main %}
            <main class="max-w-3xl px-2 mx-auto">
        {% endblock %}

        {% block main %}{% endblock %}

        {% block after_main %}
            </main>
        {% endblock %}

        {% include "_footer.html" %}
    </body>
</html>