account/urls.py
from django.urls import path

from account.views import ProfileView

app_name = 'account'

urlpatterns = [
    path('', ProfileView.as_view(), name='profile'),
]

apps/activity/urls.py
from django.urls import path

from apps.activity import views

app_name = 'activity'

urlpatterns = [
    path('<int:activity_id>/route', views.RouteView.as_view(), name='route'),
    path('<int:activity_id>/edit', views.EditView.as_view(), name='edit'),
    path('<int:activity_id>', views.DetailView.as_view(), name='detail'),
]

apps/page/urls.py
from django.urls import path

from apps.page.views import IndexView, ProfileView, RssView

app_name = 'page'

urlpatterns = [
    path('<username>/rss.xml', RssView(), name='rss'),
    path('<username>', ProfileView.as_view(), name='profile'),
    path('', IndexView.as_view(), name='index'),
]

stramate/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('grappelli/', include('grappelli.urls')),
    path('admin/', admin.site.urls),
    path('auth/', include('social_django.urls', namespace='social')),

    path('account/', include('apps.account.urls')),
    path('activity/', include('apps.activity.urls')),
    path('', include('apps.page.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/activity/models.py
from collections import defaultdict
from itertools import zip_longest
from os import path
from urllib.parse import quote_plus

import polyline
import requests
from django.conf import settings
from django.contrib.auth.models import User
from django.core.files.base import ContentFile
from django.core.files.storage import default_storage
from django.db import models
from django.urls import reverse_lazy
from django.utils.functional import cached_property

FIELD_DEFAULTS = {
    "id": 0,
    "name": "",
    "type": "",
    "description": "",
    "distance": 0,
    "moving_time": 0,
    "total_elevation_gain": 0,
    "average_speed": 0,
    "timezone": "UTC",
}


HEART_RATE_ZONES = [.6, .7, .8, .9]


class Analytic(models.Model):
    date = models.DateField()
    timezone = models.TextField()

    heatmap = models.JSONField()
    fitness = models.JSONField()

    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f"Analytics for {self.user} on {self.date}"

    class Meta:
        unique_together = (('date', 'user'),)


class Activity(models.Model):
    id = models.PositiveIntegerField(primary_key=True)

    name = models.TextField(blank=True, db_index=True)
    type = models.TextField(blank=True)
    description = models.TextField(blank=True)

    distance = models.FloatField()  # m
    moving_time = models.PositiveIntegerField()  # s
    total_elevation_gain = models.FloatField()  # m
    average_speed = models.FloatField()  # m/s

    start_date = models.DateTimeField()
    timezone = models.TextField()
    start_date_local = models.DateTimeField()
    start_location = models.TextField(blank=True, db_index=True)  # place_name

    initial_rotation = models.IntegerField(default=-10)

    # Full data
    detail = models.JSONField()
    streams = models.JSONField()

    # Analytics
    analytics = models.JSONField()

    # Relation
    athlete_id = models.PositiveIntegerField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    # Hide
    hide_map = models.BooleanField(default=False)

    @classmethod
    def upsert(cls, user_id, detail, streams):
        detail_dict = detail.to_dict()
        streams_dict = {k: v.to_dict() for k, v in streams.items()} if streams else {}

        defaults = {
            **{k: detail_dict.get(k) or v for k, v in FIELD_DEFAULTS.items()},
            "start_date": detail.start_date,
            "start_date_local": detail.start_date_local,
            "athlete_id": detail.athlete.id,
            "user_id": user_id,
            "detail": detail_dict,
            "streams": streams_dict,
            "analytics": dict(),
        }

        act, _ = Activity.objects.update_or_create(
            **defaults,
            defaults=defaults,
        )
        return act

    def get_map_file(self):
        if self.start_location:
            file_path = path.join('map', f'activity-{self.id}.png')

            if not default_storage.exists(file_path):
                self._download_map(file_path)

            return file_path

        return ""

    def get_start_location(self):
        if not self.start_location and self.polyline:
            lat, lon = self.coords[0]
            self.start_location = self._get_place_name(lat, lon)
            self.save()

        return self.start_location

    @property
    def map(self):
        return self.get_map_file()

    @property
    def coords(self):
        if self.polyline:
            return [[a, b] for (a, b) in polyline.decode(self.polyline)]
        return []

    @property
    def geojson_coords(self):
        if self.polyline:
            return [[b, a] for (a, b) in polyline.decode(self.polyline)]

        return []

    @property
    def calories(self):
        return f"{self.detail.get('calories', 0):,.0f} Cal"

    @property
    def average_hr(self):
        hr = self.detail.get('average_heartrate', 0)
        if hr:
            return f"{hr:.0f} bpm"
        return ""

    @property
    def max_hr(self):
        hr = self.detail.get('max_heartrate', 0)
        if hr:
            return f"{hr:.0f} bpm"
        return ''

    @staticmethod
    def map_zone(heartrate, max_hr, min_hr):
        [z1, z2, z3, z4] = Activity.get_zones(max_hr, min_hr)

        if not heartrate:
            return 0
        if heartrate <= z1:
            return 1
        if heartrate <= z2:
            return 2
        if heartrate <= z3:
            return 3
        if heartrate <= z4:
            return 4

        return 5

    @staticmethod
    def get_zones(max_hr, min_hr):
        hrr = max_hr - min_hr

        z1 = round((hrr * HEART_RATE_ZONES[0]) + min_hr)
        z2 = round((hrr * HEART_RATE_ZONES[1]) + min_hr)
        z3 = round((hrr * HEART_RATE_ZONES[2]) + min_hr)
        z4 = round((hrr * HEART_RATE_ZONES[3]) + min_hr)

        return [z1, z2, z3, z4]

    @cached_property
    def hr_zones_range(self):
        max_hr = self.analytics.get('max_hr')
        min_hr = self.analytics.get('min_hr')

        if not max_hr or not min_hr:
            return []

        return self.get_zones(max_hr, min_hr)

    @cached_property
    def hr_zones_colors(self):
        return [
            'rgba(156, 163, 175, 1)',
            'rgba(52, 211, 153, 1)',
            'rgba(96, 165, 250, 1)',
            'rgba(251, 191, 36, 1)',
            'rgba(248, 113, 113, 1)',
        ]

    @cached_property
    def polyline(self):
        return self.detail.get("map") and self.detail["map"].get("polyline")

    @property
    def total_distance(self):
        if self.distance > 1_000:
            return f"{self.distance/1_000:.2f} km"
        return f"{self.distance} m"

    @property
    def total_elev(self):
        if self.total_elevation_gain > 1_000:
            return f"{self.total_elevation_gain/1_000:.2f} km"
        return f"{self.total_elevation_gain:.0f} m"

    @property
    def avg_pace(self):
        pace = 1_000 / self.average_speed
        [d, h, m, s] = self._get_units(pace)
        return f"{m}:{s:02} /km"

    @property
    def max_pace(self):
        pace = 1_000 / self.max_speed
        [d, h, m, s] = self._get_units(pace)
        return f"{m}:{s:02} /km"

    @property
    def avg_speed_mps(self):
        return f"{self.average_speed:.1f} m/s"

    @property
    def avg_speed_kph(self):
        return f"{self.average_speed * 3.6:.1f} km/h"

    @property
    def max_speed_mps(self):
        return f"{self.max_speed:.1f} m/s"

    @property
    def max_speed_kph(self):
        return f"{self.max_speed * 3.6:.1f} km/h"

    @cached_property
    def max_speed(self):
        return self.detail.get("max_speed", 0)

    @staticmethod
    def format_time(seconds):
        fdiff = ''
        [d, h, m, s] = Activity._get_units(seconds)

        if d > 0:
            fdiff += f'{d}d'

        if h > 0:
            fdiff += f' {h}h'

        if m > 0:
            fdiff += f' {m}m'

        if s > 0:
            fdiff += f' {s}s'

        return fdiff.strip()

    @property
    def total_moving_time(self):
        return self.format_time(self.moving_time)

    @cached_property
    def heart_rate_zones(self):
        hr_zones = self.analytics.get("hr_zones")
        if not hr_zones:
            return []

        zones = defaultdict(int)
        total_time = len(hr_zones)
        for z in hr_zones:
            zones[z] += 1

        zones_range = [
            f"< {l} bpm" if not h else f"{h} bpm - {l} bpm" if l else f"> {h} bpm"
            for [l, h] in zip_longest(self.hr_zones_range, [None] + self.hr_zones_range)
        ]

        zones_colors = self.hr_zones_colors
        zones_bg = [c.replace(', 1)', ', 0.4)') for c in zones_colors]

        return [
            {
                "zone": i,
                "zonef": f"Zone {i}",
                "time": zones[i],
                "timef": self.format_time(zones[i]),
                "percent": f"{zones[i] / total_time * 100:.0f}%",
                "color": zones_colors[i - 1],
                "bg": zones_bg[i - 1],
                "range": zones_range[i - 1],
            }
            for i in [1, 2, 3, 4, 5]
        ]

    @property
    def stress_score(self):
        hrss = self.analytics.get("hrss")
        if hrss:
            return f"{hrss:.1f}"
        return "N/A"

    @staticmethod
    def _get_units(diff):
        d = int(diff / 86_400)
        h = int((diff - (d * 86_400)) / 3_600)
        m = int((diff - (d * 86_400 + h * 3_600)) / 60)
        s = int((diff - (d * 86_400 + h * 3_600 + m * 60)))
        return [d, h, m, s]

    def _get_place_name(self, lat, lon):
        at = settings.MAPBOX_ACCESS_TOKEN
        url = f"https://api.mapbox.com/geocoding/v5/mapbox.places/{lon},{lat}.json?types=place,region&access_token={at}"
        res = requests.get(url)
        geo = res.json()

        return geo['features'] and geo['features'][0] and geo['features'][0]['place_name'] or "Unknown"

    def _download_map(self, file_path):
        at = settings.MAPBOX_ACCESS_TOKEN
        pl = quote_plus(self.detail["map"]["polyline"])
        url = f"https://api.mapbox.com/styles/v1/mapbox/outdoors-v11/static/path-3+30a14e-1({pl})/auto/1000x400@2x?padding=50&access_token={at}"

        with requests.get(url, stream=True) as r:
            r.raise_for_status()

            default_storage.save(file_path, ContentFile(b''))  # Trick to create file

            with default_storage.open(file_path, 'wb') as f:
                for chunk in r.iter_content(chunk_size=8192):
                    f.write(chunk)

        return path

    def get_absolute_url(self):
        return reverse_lazy("activity:detail", args=(self.id,))

    def __str__(self):
        return f"{self.type} #{self.id}: {self.name}"

    class Meta:
        verbose_name_plural = "activities"

apps/activity/forms.py
from django import forms
from django.forms.widgets import Textarea, TextInput, NumberInput, CheckboxInput
from apps.activity.models import Activity


class ActivityForm(forms.ModelForm):
    name = forms.Field(widget=TextInput(attrs={'class': "form-control form-block"}))
    description = forms.Field(
        required=False,
        widget=Textarea(attrs={'class': "form-control form-block"}),
    )
    initial_rotation = forms.IntegerField(
        required=False,
        widget=NumberInput(attrs={'class': "form-control form-block"}),
    )
    hide_map = forms.BooleanField(
        required=False,
        widget=CheckboxInput(attrs={'class': "form-control form-checkbox"}),
    )

    class Meta:
        model = Activity
        fields = ['name', 'description', 'hide_map', 'initial_rotation']

apps/activity/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404
from django.shortcuts import get_object_or_404
from django.views.generic import TemplateView, DetailView
from django.views.generic.edit import UpdateView

from apps.activity.forms import ActivityForm
from apps.activity.models import Activity


class RouteView(TemplateView):
    template_name = "activity/route.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        activity_id = kwargs.get('activity_id')
        activity = get_object_or_404(Activity, id=activity_id)

        if self.request.user == activity.user or not activity.hide_map:
            context["activity"] = activity
            return context

        raise Http404()


class DetailView(DetailView):
    model = Activity
    pk_url_kwarg = "activity_id"
    template_name = "activity/detail.html"


class EditView(LoginRequiredMixin, UpdateView):
    model = Activity
    form_class = ActivityForm
    pk_url_kwarg = "activity_id"
    template_name = "activity/edit.html"

    def get_object(self, **kwargs):
        obj = super().get_object(**kwargs)
        if obj.user != self.request.user:
            raise Http404()
        return obj

theme/templates/page/_activity.html
{% load humanize %}
{% load heroicons %}
{% load static %}

<li class="relative px-4 py-6 border rounded bg-gray-50 space-y-4">
  <section class="flex items-center justify-between space-x-2">
    {% include "page/_activity_date.html" %}
    {% if request.user == activity.user %}
      <a href="{% url "activity:detail" activity.id %}"
         class="opacity-50 text-link"
         title="View this activity">
        {% heroicon_outline "link" class="w-4 h-4" %}
      </a>
    {% endif %}
  </section>
  <h3 class="flex items-center text-xl font-bold justify-stretch space-x-3">
    <span class="flex-shrink-0">
    {% if activity.type == "Ride" %}
      {% include "page/ride.svg" %}
    {% elif activity.type == "Run" %}
      {% include "page/run.svg" %}
    {% elif activity.type == "Swim" %}
      {% include "page/swim.svg" %}
    {% elif activity.type == "Hike" %}
      {% include "page/hike.svg" %}
    {% elif activity.type == "Walk" %}
      {% include "page/walk.svg" %}
    {% else %}
      {% include "page/activity.svg" %}
    {% endif %}
    </span>
    <p>{{ activity.name }}</p>
  </h3>
  <section class="flex items-start justify-start">
    <section class="pr-4 border-r">
      {% if activity.distance %}
        <h4 class="text-xs">Distance</h4>
        <p class="text-base">{{ activity.format_distance }}</p>
      {% else %}
        <h4 class="text-xs">Cal</h4>
        <p class="text-base">{{ activity.calories|intcomma }}</p>
      {% endif %}
    </section>
    <section class="px-4 border-r">
      {% if activity.type == "Ride" %}
        <h4 class="text-xs">Elev. gain</h4>
        <p class="text-base">{{ activity.format_elev }}</p>
      {% elif activity.type == "Run" %}
        <h4 class="text-xs">Pace</h4>
        <p class="text-base">{{ activity.format_pace }}</p>
      {% elif activity.distance %}
        <h4 class="text-xs">Speed</h4>
        <p class="text-base">{{ activity.format_speed }}</p>
      {% else %}
        <h4 class="text-xs">Avg. HR</h4>
        <p class="text-base">{{ activity.average_hr }}</p>
      {% endif %}
    </section>
    <section class="px-4">
      <h4 class="text-xs">Time</h4>
      <p class="text-base">{{ activity.format_moving_time }}</p>
    </section>
  </section>
  {% include "page/_activity_map.html" %}
<li>

theme/templates/page/_activity_heart.html
<canvas style="" id="heart"></canvas>

<script src="//cdn.jsdelivr.net/npm/chart.js@3.5.1/dist/chart.min.js"></script>
<script>
  const data = {{ activity.heart_rate_zones|safe }};
  const config = {
    type: 'doughnut',
    options: {
      plugins: {
        legend: true,
        tooltip: {
          callbacks: {
            label(context) {
                return data[context.dataIndex].timef;
            },
          },
        },
      },
    },
    data: {
      datasets: [{
        data: data.map(d => d.time),
        backgroundColor: [
          'rgb(254, 202, 202)',
          'rgb(252, 165, 165)',
          'rgb(248, 113, 113)',
          'rgb(239, 68, 68)',
          'rgb(220, 38, 38)',
        ],
      }],
      labels: data.map(d => d.zonef),
    },
  };
  var ctx = document.getElementById('heart').getContext('2d');
  var chart = new Chart(ctx, config);
</script>

theme/templates/page/_heatmap.html
{% load humanize %}
{% load heroicons %}

<section class="mb-8 space-y-2">
  <section class="flex items-center justify-between space-x-4">
    <h2 class="flex items-center justify-start text-lg space-x-1">
      {% heroicon_outline "chart-bar" class="w-4 h-4 opacity-70" %}
      <span>{{ last_year_total|intcomma }} activities in the last year</span>
    </h2>
    <a href="{% url "page:rss" username %}" class="opacity-50" />
      {% heroicon_outline "rss" class="w-4 h-4" %}
    </a>
  </section>

  <section class="flex items-center justify-end px-4 overflow-hidden bg-white border rounded">
    <section style="width: 718px; height: 143px;">
      <canvas id="heatmap" style="width: 718px; height: 143px;"></canvas>
    </section>
  </section>
</section>

{% if request.user.username == username or show_fitness_chart %}
<section class="mb-8 space-y-2">
  <section class="flex items-center justify-between space-x-4">
    <h2 class="flex items-center justify-start text-lg space-x-1">
      {% heroicon_outline "lightning-bolt" class="w-4 h-4 opacity-70" %}

      <span class="text-green-700">Fitness {{ today.ctl|floatformat:"0" }}</span>
      <span>&middot;</span>
      <span class="text-gray-700">Fatigue {{ today.atl|floatformat:"0" }}</span>
      <span>&middot;</span>
      <span class="text-blue-700">Form {{ today.tsb|floatformat:"0" }}</span>
    </h2>
    <a href="https://github.com/manhtai/stramate/wiki/Training-load:-Fitness-&-Fatigue" class="opacity-50 text-link" title="Fitness and fatigue" target="new">
      {% heroicon_outline "information-circle" class="w-4 h-4" %}
    </a>
  </section>

  <section class="flex items-center justify-end px-4 overflow-hidden bg-white border rounded">
    <section style="width: 718px; height: 400px;">
      <canvas style="width: 718px; height: 400px;" id="fitness"></canvas>
    </section>
  </section>
</section>
{% endif %}

<script src="//cdn.jsdelivr.net/npm/chart.js@3.5.1/dist/chart.min.js"></script>
<script src="//cdn.jsdelivr.net/npm/chartjs-adapter-date-fns@2.0.0/dist/chartjs-adapter-date-fns.bundle.min.js"></script>
<script src="//cdn.jsdelivr.net/npm/chartjs-chart-matrix@1.1.0/dist/chartjs-chart-matrix.min.js"></script>

<script>
  // ==================== Heatmap start ====================
  const scales = {
    y: {
      type: 'time',
      offset: true,
      time: {
        unit: 'day',
        round: 'day',
        isoWeekday: 0,
        parser: function(w) {
          const d = new Date();
          const diff = w - d.getDay();
          d.setDate(d.getDate() + diff);
          return d
        },
        displayFormats: {
          day: 'iii'
        }
      },
      reverse: true,
      position: 'left',
      ticks: {
        source: 'data',
        maxRotation: 0,
        autoSkip: true,
        padding: 4,
        crossAlign: 'far',
        font: {
          size: 9,
        },
        callback: function(value, index, values) {
          return ['Mon', 'Wed', 'Fri'].indexOf(value) > -1 ? value : '';
        },
      },
      grid: {
        display: false,
        drawBorder: false,
        tickLength: 0
      },
    },
    x: {
      type: 'time',
      position: 'bottom',
      offset: true,
      display: false,
      time: {
        unit: 'week',
        round: 'week',
        isoWeekday: 0,
        displayFormats: {
          week: 'MMM'
        }
      },
      grid: {
        display: false,
        drawBorder: false,
        tickLength: 0,
      }
    }
  };

  const options = {
    responsive: false,
    aspectRatio: 5,
    plugins: {
      legend: false,
      tooltip: {
        displayColors: false,
        callbacks: {
          title() {
            return '';
          },
          label(context) {
            const v = context.dataset.data[context.dataIndex];
            return [
              (!v.v ? "No activities" : "Moved for " + v.l) + " on " + v.d,
            ];
          }
        }
      },
    },
    scales: scales,
    layout: {
      padding: {
        top: 4,
        bottom: 4,
      }
    }
  };


  const bgColors = ['#ebedf0', '#9be98a', '#40c463', '#30a14e', '#216e39'];
  const bdColors = ['#dee0e4', '#93dca0', '#3dba5f', '#30a14e', '#206938'];

  const getColor = (v, maxV, colors) => {
    const step = maxV / colors.length;
    for (let i = 0; i < colors.length; i++) {
        if (v <= i * step) {
            return colors[i]
        }
    }
    return colors[colors.length-1]
  }

  const getBgColor = (c) => {
    const value = c.dataset.data[c.dataIndex].v;
    return getColor(value, 7200, bgColors);
  }

  const getBorderColor = (c) => {
    const value = c.dataset.data[c.dataIndex].v;
    return getColor(value, 7200, bdColors);
  }

  const data = {
    datasets: [{
      label: 'Moving time',
      data: {{ last_year_moving|safe }},
      backgroundColor(c) {
          return getBgColor(c);
      },
      borderColor(c) {
          return getBorderColor(c);
      },
      borderWidth: 1,
      hoverBackgroundColor(c) {
          return getBgColor(c);
      },
      hoverBorderColor(c) {
          return getBgColor(c);
      },
      width(c) {
        const a = c.chart.chartArea || {};
        return (a.right - a.left) / 52 - 2;
      },
      height(c) {
        const a = c.chart.chartArea || {};
        return (a.bottom - a.top) / 8 - 3;
      },
      borderRadius: 3,
    }]
  };


  const config = {
    type: 'matrix',
    data: data,
    options: options
  };

  var ctx = document.getElementById('heatmap').getContext('2d');
  var heatmap = new Chart(ctx, config);
  // ==================== Heatmap end ======================

  // ==================== Fitness start ====================
  const ftData = {{ fitness|safe }};
  const ctlData = ftData.map(d => d.ctl.toFixed(0));
  const atlData = ftData.map(d => d.atl.toFixed(0));
  const tsbData = ftData.map(d => d.tsb.toFixed(0));

  const suggestedMax = Math.max(Math.max(...ctlData), Math.max(...atlData));
  const suggestedMin = Math.min(...tsbData);

  const ftConfig = {
    type: 'line',
    data: {
      labels: ftData.map(o => o.x),
      datasets: [
        {
          label: "Fitness",
          data: ctlData,
          yAxisID: 'ctl',
          borderColor: bdColors[2],
          backgroundColor: bgColors[2],
          borderWidth: 2,
          pointRadius: 0,
        },
        {
          label: "Fatigue",
          data: atlData,
          yAxisID: 'atl',
          borderColor: bdColors[0],
          backgroundColor: bgColors[0],
          borderWidth: 1,
          pointRadius: 0,
        },
        {
          label: "Form",
          data: tsbData,
          yAxisID: 'tsb',
          borderColor: "rgba(59, 130, 246, 0.5)",
          backgroundColor: "rgba(96, 165, 250, 0.9)",
          borderWidth: 1,
          pointRadius: 0,
        },
      ]
    },
    options: {
      responsive: true,
      interaction: {
        mode: 'index',
        intersect: false,
      },
      plugins:{
        legend: false,
        tooltip: {
          callbacks: {
            title([x, y]) {
              return x.label.split(',').slice(0, 2).join(',');
            },
          },
        },
      },
      stacked: false,
      scales: {
        x: {
          offset: true,
          type: 'time',
          grid: {
            display: false,
            drawBorder: false,
            tickLength: 0,
          },
          ticks: {
            autoSkip: true,
            font: {
              size: 9,
            },
          },
        },
        ctl: {
          offset: true,
          display: true,
          position: 'left',
          grid: {
            display: true,
            drawBorder: false,
          },
          suggestedMax,
          suggestedMin,
        },
        atl: {
          offset: true,
          display: true,
          position: 'right',
          grid: {
            drawBorder: false,
            tickLength: 0,
            display: false,
          },
          suggestedMax,
          suggestedMin,
        },
        tsb: {
          offset: true,
          display: false,
          position: 'right',
          grid: {
            drawBorder: false,
            tickLength: 0,
          },
          suggestedMax,
          suggestedMin,
        },
      },
      layout: {
        padding: {
          top: 30,
          bottom: 30,
        }
      },
    },
  };

  var ftCtx = document.getElementById('fitness').getContext('2d');
  var ftChart = new Chart(ftCtx, ftConfig);
  // ==================== Fitness end ======================
</script>

theme/templates/page/_recent.html
{% load humanize %}
{% load heroicons %}
{% load add_query_to_url %}

<section class="mb-8 space-y-2">
  <section class="flex flex-wrap items-center justify-between">
    <h2 class="flex items-center justify-start mr-4 text-lg space-x-1">
      {% heroicon_outline "calendar" class="w-4 h-4 opacity-70" %}
      <span>Latest activities</span>
    </h2>
    {% if request.user.username == username %}
    <form>
      <input
        placeholder="Type to search..."
        type="text"
        name="q"
        class="form-control form-block opacity-70"
        value="{{ request.GET.q }}"
      />
    </form>
    {% endif %}
  </section>

  <ul class="space-y-4">
    {% for activity in page_obj %}
      {% include "activity/_activity.html" %}
    {% endfor %}
  </ul>
</section>


<section class="pagination__wrapper">
  <p>
    Total: {{ all_time_total|intcomma }} activities
  </p>

  <ul class="pagination__button">
    {% if page_obj.number %}
      {% if page_obj.has_previous %}
        {% if page_obj.previous_page_number != 1 %}
          <a href="{% add_query_to_url page=1 %}" class="pagination__nav">
            {% heroicon_outline "chevron-double-left" class="w-6 h-6" %}
          </a>
        {% endif %}
        <a href="{% add_query_to_url page=page_obj.previous_page_number %}" class="pagination__nav">
          {% heroicon_outline "chevron-left" class="w-6 h-6" %}
        </a>
      {% endif %}

      <span class="px-2 text-center">
        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
      </span>

      {% if page_obj.has_next %}
        <a href="{% add_query_to_url page=page_obj.next_page_number %}" class="pagination__nav">
          {% heroicon_outline "chevron-right" class="w-6 h-6" %}
        </a>

        {% if page_obj.next_page_number != page_obj.paginator.num_pages %}
          <a href="{% add_query_to_url page=page_obj.paginator.num_pages %}" class="pagination__nav">
            {% heroicon_outline "chevron-double-right" class="w-6 h-6" %}
          </a>
        {% endif %}
      {% endif %}
    {% endif %}
  </ul>
</section>

theme/templates/page/profile.html
{% extends "base.html" %}

{% load heroicons %}
{% load humanize %}

{% block title %}{{ username }}{% endblock %}

{% block main %}
  <section class="flex flex-wrap items-center justify-between my-10 leading-10">
    <a class="text-4xl font-bold" href="{% url "page:profile" username %}">
      {{ username }}
    </a>
    <p class="flex items-center justify-center space-x-3 opacity-80">
      <span class="flex items-center justify-center space-x-1">
        {% include "activity/run.svg" %}
        <span>{{ all_time_distance.Run|intcomma }} km</span>
      </span>
      <span class="flex items-center justify-center space-x-1">
        {% include "activity/ride.svg" %}
        <span>{{ all_time_distance.Ride|intcomma }} km</span>
      </span>
      <span class="flex items-center justify-center space-x-1">
        {% include "activity/swim.svg" %}
        <span>{{ all_time_distance.Swim|intcomma }} km</span>
      </span>
    </p>
  </section>

  {% if not request.GET.page and not request.GET.q %}
    {% include "page/_heatmap.html" %}
  {% endif %}

  {% include "page/_recent.html" %}
{% endblock %}