account/urls.py
from django.urls import path

from account.views import ProfileView

app_name = 'account'

urlpatterns = [
    path('', ProfileView.as_view(), name='profile'),
]

apps/activity/urls.py
from django.urls import path

from apps.activity import views

app_name = 'activity'

urlpatterns = [
    path('<int:activity_id>/route', views.RouteView.as_view(), name='route'),
    path('<int:activity_id>/edit', views.EditView.as_view(), name='edit'),
    path('<int:activity_id>', views.DetailView.as_view(), name='detail'),
]

stramate/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('grappelli/', include('grappelli.urls')),
    path('admin/', admin.site.urls),
    path('auth/', include('social_django.urls', namespace='social')),

    path('account/', include('apps.account.urls')),
    path('activity/', include('apps.activity.urls')),
    path('', include('apps.page.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/activity/models.py
from collections import defaultdict
from itertools import zip_longest
from os import path
from urllib.parse import quote_plus

import polyline
import requests
from django.conf import settings
from django.contrib.auth.models import User
from django.core.files.base import ContentFile
from django.core.files.storage import default_storage
from django.db import models
from django.urls import reverse_lazy
from django.utils.functional import cached_property

FIELD_DEFAULTS = {
    "id": 0,
    "name": "",
    "type": "",
    "description": "",
    "distance": 0,
    "moving_time": 0,
    "total_elevation_gain": 0,
    "average_speed": 0,
    "timezone": "UTC",
}


HEART_RATE_ZONES = [.6, .7, .8, .9]


class Analytic(models.Model):
    date = models.DateField()
    timezone = models.TextField()

    heatmap = models.JSONField()
    fitness = models.JSONField()

    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f"Analytics for {self.user} on {self.date}"

    class Meta:
        unique_together = (('date', 'user'),)


class Activity(models.Model):
    id = models.PositiveIntegerField(primary_key=True)

    name = models.TextField(blank=True, db_index=True)
    type = models.TextField(blank=True)
    description = models.TextField(blank=True)

    distance = models.FloatField()  # m
    moving_time = models.PositiveIntegerField()  # s
    total_elevation_gain = models.FloatField()  # m
    average_speed = models.FloatField()  # m/s

    start_date = models.DateTimeField()
    timezone = models.TextField()
    start_date_local = models.DateTimeField()
    start_location = models.TextField(blank=True, db_index=True)  # place_name

    initial_rotation = models.IntegerField(default=-10)

    # Full data
    detail = models.JSONField()
    streams = models.JSONField()

    # Analytics
    analytics = models.JSONField()

    # Relation
    athlete_id = models.PositiveIntegerField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    # Hide
    hide_map = models.BooleanField(default=False)

    @classmethod
    def upsert(cls, user_id, detail, streams):
        detail_dict = detail.to_dict()
        streams_dict = {k: v.to_dict() for k, v in streams.items()} if streams else {}

        defaults = {
            **{k: detail_dict.get(k) or v for k, v in FIELD_DEFAULTS.items()},
            "start_date": detail.start_date,
            "start_date_local": detail.start_date_local,
            "athlete_id": detail.athlete.id,
            "user_id": user_id,
            "detail": detail_dict,
            "streams": streams_dict,
            "analytics": dict(),
        }

        act, _ = Activity.objects.update_or_create(
            **defaults,
            defaults=defaults,
        )
        return act

    def get_map_file(self):
        if self.start_location:
            file_path = path.join('map', f'activity-{self.id}.png')

            if not default_storage.exists(file_path):
                self._download_map(file_path)

            return file_path

        return ""

    def get_start_location(self):
        if not self.start_location and self.polyline:
            lat, lon = self.coords[0]
            self.start_location = self._get_place_name(lat, lon)
            self.save()

        return self.start_location

    @property
    def map(self):
        return self.get_map_file()

    @property
    def coords(self):
        if self.polyline:
            return [[a, b] for (a, b) in polyline.decode(self.polyline)]
        return []

    @property
    def geojson_coords(self):
        if self.polyline:
            return [[b, a] for (a, b) in polyline.decode(self.polyline)]

        return []

    @property
    def calories(self):
        return f"{self.detail.get('calories', 0):,.0f} Cal"

    @property
    def average_hr(self):
        hr = self.detail.get('average_heartrate', 0)
        if hr:
            return f"{hr:.0f} bpm"
        return ""

    @property
    def max_hr(self):
        hr = self.detail.get('max_heartrate', 0)
        if hr:
            return f"{hr:.0f} bpm"
        return ''

    @staticmethod
    def map_zone(heartrate, max_hr, min_hr):
        [z1, z2, z3, z4] = Activity.get_zones(max_hr, min_hr)

        if not heartrate:
            return 0
        if heartrate <= z1:
            return 1
        if heartrate <= z2:
            return 2
        if heartrate <= z3:
            return 3
        if heartrate <= z4:
            return 4

        return 5

    @staticmethod
    def get_zones(max_hr, min_hr):
        hrr = max_hr - min_hr

        z1 = round((hrr * HEART_RATE_ZONES[0]) + min_hr)
        z2 = round((hrr * HEART_RATE_ZONES[1]) + min_hr)
        z3 = round((hrr * HEART_RATE_ZONES[2]) + min_hr)
        z4 = round((hrr * HEART_RATE_ZONES[3]) + min_hr)

        return [z1, z2, z3, z4]

    @cached_property
    def hr_zones_range(self):
        max_hr = self.analytics.get('max_hr')
        min_hr = self.analytics.get('min_hr')

        if not max_hr or not min_hr:
            return []

        return self.get_zones(max_hr, min_hr)

    @cached_property
    def hr_zones_colors(self):
        return [
            'rgba(156, 163, 175, 1)',
            'rgba(52, 211, 153, 1)',
            'rgba(96, 165, 250, 1)',
            'rgba(251, 191, 36, 1)',
            'rgba(248, 113, 113, 1)',
        ]

    @cached_property
    def polyline(self):
        return self.detail.get("map") and self.detail["map"].get("polyline")

    @property
    def total_distance(self):
        if self.distance > 1_000:
            return f"{self.distance/1_000:.2f} km"
        return f"{self.distance} m"

    @property
    def total_elev(self):
        if self.total_elevation_gain > 1_000:
            return f"{self.total_elevation_gain/1_000:.2f} km"
        return f"{self.total_elevation_gain:.0f} m"

    @property
    def avg_pace(self):
        pace = 1_000 / self.average_speed
        [d, h, m, s] = self._get_units(pace)
        return f"{m}:{s:02} /km"

    @property
    def max_pace(self):
        pace = 1_000 / self.max_speed
        [d, h, m, s] = self._get_units(pace)
        return f"{m}:{s:02} /km"

    @property
    def avg_speed_mps(self):
        return f"{self.average_speed:.1f} m/s"

    @property
    def avg_speed_kph(self):
        return f"{self.average_speed * 3.6:.1f} km/h"

    @property
    def max_speed_mps(self):
        return f"{self.max_speed:.1f} m/s"

    @property
    def max_speed_kph(self):
        return f"{self.max_speed * 3.6:.1f} km/h"

    @cached_property
    def max_speed(self):
        return self.detail.get("max_speed", 0)

    @staticmethod
    def format_time(seconds):
        fdiff = ''
        [d, h, m, s] = Activity._get_units(seconds)

        if d > 0:
            fdiff += f'{d}d'

        if h > 0:
            fdiff += f' {h}h'

        if m > 0:
            fdiff += f' {m}m'

        if s > 0:
            fdiff += f' {s}s'

        return fdiff.strip()

    @property
    def total_moving_time(self):
        return self.format_time(self.moving_time)

    @cached_property
    def heart_rate_zones(self):
        hr_zones = self.analytics.get("hr_zones")
        if not hr_zones:
            return []

        zones = defaultdict(int)
        total_time = len(hr_zones)
        for z in hr_zones:
            zones[z] += 1

        zones_range = [
            f"< {l} bpm" if not h else f"{h} bpm - {l} bpm" if l else f"> {h} bpm"
            for [l, h] in zip_longest(self.hr_zones_range, [None] + self.hr_zones_range)
        ]

        zones_colors = self.hr_zones_colors
        zones_bg = [c.replace(', 1)', ', 0.4)') for c in zones_colors]

        return [
            {
                "zone": i,
                "zonef": f"Zone {i}",
                "time": zones[i],
                "timef": self.format_time(zones[i]),
                "percent": f"{zones[i] / total_time * 100:.0f}%",
                "color": zones_colors[i - 1],
                "bg": zones_bg[i - 1],
                "range": zones_range[i - 1],
            }
            for i in [1, 2, 3, 4, 5]
        ]

    @property
    def stress_score(self):
        hrss = self.analytics.get("hrss")
        if hrss:
            return f"{hrss:.1f}"
        return "N/A"

    @staticmethod
    def _get_units(diff):
        d = int(diff / 86_400)
        h = int((diff - (d * 86_400)) / 3_600)
        m = int((diff - (d * 86_400 + h * 3_600)) / 60)
        s = int((diff - (d * 86_400 + h * 3_600 + m * 60)))
        return [d, h, m, s]

    def _get_place_name(self, lat, lon):
        at = settings.MAPBOX_ACCESS_TOKEN
        url = f"https://api.mapbox.com/geocoding/v5/mapbox.places/{lon},{lat}.json?types=place,region&access_token={at}"
        res = requests.get(url)
        geo = res.json()

        return geo['features'] and geo['features'][0] and geo['features'][0]['place_name'] or "Unknown"

    def _download_map(self, file_path):
        at = settings.MAPBOX_ACCESS_TOKEN
        pl = quote_plus(self.detail["map"]["polyline"])
        url = f"https://api.mapbox.com/styles/v1/mapbox/outdoors-v11/static/path-3+30a14e-1({pl})/auto/1000x400@2x?padding=50&access_token={at}"

        with requests.get(url, stream=True) as r:
            r.raise_for_status()

            default_storage.save(file_path, ContentFile(b''))  # Trick to create file

            with default_storage.open(file_path, 'wb') as f:
                for chunk in r.iter_content(chunk_size=8192):
                    f.write(chunk)

        return path

    def get_absolute_url(self):
        return reverse_lazy("activity:detail", args=(self.id,))

    def __str__(self):
        return f"{self.type} #{self.id}: {self.name}"

    class Meta:
        verbose_name_plural = "activities"

apps/activity/forms.py
from django import forms
from django.forms.widgets import Textarea, TextInput, NumberInput, CheckboxInput
from apps.activity.models import Activity


class ActivityForm(forms.ModelForm):
    name = forms.Field(widget=TextInput(attrs={'class': "form-control form-block"}))
    description = forms.Field(
        required=False,
        widget=Textarea(attrs={'class': "form-control form-block"}),
    )
    initial_rotation = forms.IntegerField(
        required=False,
        widget=NumberInput(attrs={'class': "form-control form-block"}),
    )
    hide_map = forms.BooleanField(
        required=False,
        widget=CheckboxInput(attrs={'class': "form-control form-checkbox"}),
    )

    class Meta:
        model = Activity
        fields = ['name', 'description', 'hide_map', 'initial_rotation']

apps/activity/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404
from django.shortcuts import get_object_or_404
from django.views.generic import TemplateView, DetailView
from django.views.generic.edit import UpdateView

from apps.activity.forms import ActivityForm
from apps.activity.models import Activity


class RouteView(TemplateView):
    template_name = "activity/route.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        activity_id = kwargs.get('activity_id')
        activity = get_object_or_404(Activity, id=activity_id)

        if self.request.user == activity.user or not activity.hide_map:
            context["activity"] = activity
            return context

        raise Http404()


class DetailView(DetailView):
    model = Activity
    pk_url_kwarg = "activity_id"
    template_name = "activity/detail.html"


class EditView(LoginRequiredMixin, UpdateView):
    model = Activity
    form_class = ActivityForm
    pk_url_kwarg = "activity_id"
    template_name = "activity/edit.html"

    def get_object(self, **kwargs):
        obj = super().get_object(**kwargs)
        if obj.user != self.request.user:
            raise Http404()
        return obj

theme/templates/activity/_activity.html
{% load heroicons %}
{% load static %}

<li class="relative px-4 py-6 bg-white border rounded bg-gray-50 space-y-4">
  <section class="flex items-start justify-between space-x-2">
    {% include "activity/_activity_date.html" %}
  </section>

  <h3 class="flex items-center text-xl font-bold justify-stretch space-x-3">
    <span class="flex-shrink-0">
    {% if activity.type == "Ride" %}
      {% include "activity/ride.svg" %}
    {% elif activity.type == "Run" %}
      {% include "activity/run.svg" %}
    {% elif activity.type == "Swim" %}
      {% include "activity/swim.svg" %}
    {% elif activity.type == "Hike" %}
      {% include "activity/hike.svg" %}
    {% elif activity.type == "Walk" %}
      {% include "activity/walk.svg" %}
    {% else %}
      {% include "activity/activity.svg" %}
    {% endif %}
    </span>
    <a href="{% url "activity:detail" activity.id %}" class="text-link">
      <p>{{ activity.name }}</p>
    </a>
  </h3>

  {% include "activity/_activity_desc.html" %}
  {% include "activity/_activity_map.html" %}
<li>

theme/templates/activity/_activity_date.html
{% load tz %}
{% load heroicons %}
{% load humanize %}

<p class="text-xs">
  {% timezone activity.timezone %}
    {{ activity.start_date|naturalday|title }} at
    {{ activity.start_date|date:"P" }}
  {% endtimezone %}
  {% if activity.start_location %} &middot; {{ activity.start_location }}{% endif %}
</p>

theme/templates/activity/_activity_desc.html
{% load humanize %}

<section class="flex items-start justify-start">
  <section class="pr-4 border-r">
    {% if activity.distance %}
      <h4 class="text-xs">Distance</h4>
      <p class="text-base">{{ activity.total_distance }}</p>
    {% else %}
      <h4 class="text-xs">Calories</h4>
      <p class="text-base">{{ activity.calories|intcomma }}</p>
    {% endif %}
  </section>
  <section class="px-4 border-r">
    {% if activity.type == "Ride" %}
      <h4 class="text-xs">Elev. gain</h4>
      <p class="text-base">{{ activity.total_elev }}</p>
    {% elif activity.type == "Run" %}
      <h4 class="text-xs">Pace</h4>
      <p class="text-base">{{ activity.avg_pace }}</p>
    {% elif activity.type == "Swim" %}
      <h4 class="text-xs">Speed</h4>
      <p class="text-base">{{ activity.avg_speed_mps }}</p>
    {% elif activity.distance %}
      <h4 class="text-xs">Speed</h4>
      <p class="text-base">{{ activity.avg_speed_kph }}</p>
    {% elif activity.max_hr %}
      <h4 class="text-xs">Avg. HR</h4>
      <p class="text-base">{{ activity.average_hr }}</p>
    {% endif %}
  </section>
  <section class="px-4">
    <h4 class="text-xs">Time</h4>
    <p class="text-base">{{ activity.total_moving_time }}</p>
  </section>
</section>

theme/templates/activity/_activity_detail.html
{% load tz %}
{% load humanize %}
{% load heroicons %}

<li class="relative px-4 py-6 bg-white border rounded bg-gray-50 space-y-4">
  {% include "activity/_activity_map.html" %}

  <section class="flex items-start justify-between space-x-2">
    {% include "activity/_activity_date.html" %}

    {% if request.user == activity.user %}
    <a href="{% url "activity:edit" activity.id %}"
       class="opacity-50 text-link"
       title="Edit this activity">
      {% heroicon_outline "pencil-alt" class="w-4 h-4" %}
    </a>
    {% endif %}
  </section>

  <section class="flex flex-col items-start justify-around space-y-10">
    <section class="flex flex-col space-y-4">
      <h3 class="text-xl font-bold">
        Metrics
      </h3>

      <section class="flex flex-wrap items-start justify-start">
        <section class="pr-8 mb-4">
          <h4 class="text-xs">Time</h4>
          <p class="text-base">{{ activity.total_moving_time }}</p>
        </section>
        <section class="pr-8 mb-4">
          <h4 class="text-xs">Calories</h4>
          <p class="text-base">{{ activity.calories|intcomma }}</p>
        </section>
        {% if activity.max_hr %}
        <section class="pr-8 mb-4">
          <h4 class="text-xs">Avg. HR</h4>
          <p class="text-base">{{ activity.average_hr }}</p>
        </section>
        <section class="pr-8 mb-4">
          <h4 class="text-xs">Max HR</h4>
          <p class="text-base">{{ activity.max_hr }}</p>
        </section>
        {% endif %}
      </section>

      {% if activity.distance %}
      <section class="flex flex-wrap items-start justify-start">
        <section class="pr-8 mb-4">
          <h4 class="text-xs">Distance</h4>
          <p class="text-base">{{ activity.total_distance }}</p>
        </section>

        <section class="pr-8 mb-4">
          <h4 class="text-xs">Elev. gain</h4>
          <p class="text-base">{{ activity.total_elev }}</p>
        </section>

        {% if activity.type == "Run" %}
          <section class="pr-8 mb-4">
            <h4 class="text-xs">Avg. pace</h4>
            <p class="text-base">{{ activity.avg_pace }}</p>
          </section>
          <section class="pr-8 mb-4">
            <h4 class="text-xs">Max pace</h4>
            <p class="text-base">{{ activity.max_pace }}</p>
          </section>
        {% elif activity.type == "Swim" %}
          <section class="pr-8 mb-4">
            <h4 class="text-xs">Avg. speed</h4>
            <p class="text-base">{{ activity.avg_speed_mps }}</p>
          </section>
          <section class="pr-8 mb-4">
            <h4 class="text-xs">Max speed</h4>
            <p class="text-base">{{ activity.max_speed_mps }}</p>
          </section>
        {% else %}
          <section class="pr-8 mb-4">
            <h4 class="text-xs">Avg. speed</h4>
            <p class="text-base">{{ activity.avg_speed_kph }}</p>
          </section>
          <section class="pr-8 mb-4">
            <h4 class="text-xs">Max speed</h4>
            <p class="text-base">{{ activity.max_speed_kph }}</p>
          </section>
        {% endif %}
      </section>
      {% endif %}
    </section>

    {% if activity.max_hr %}
      {% if request.user == activity.user %}
      <section class="flex flex-col space-y-4">
        <h3 class="text-xl font-bold">
          Heart rate zones
        </h3>
        <section>
          {% include "activity/_activity_heart.html" %}
        </section>
      </section>
      {% endif %}

      <section class="flex flex-col space-y-4">
        <h3 class="text-xl font-bold">
          Stress score
        </h3>
        <section>
          <p class="text-lg">{{ activity.stress_score }}<p>
        </section>
      </section>
    {% endif %}
  </section>
<li>

theme/templates/activity/_activity_heart.html
<canvas class="my-4" id="heart"></canvas>
<section>
  {% for z in activity.heart_rate_zones|slice:"::-1" %}
  <div class="relative pt-1">
    <div class="flex items-center justify-between mb-2">
      <div>
        <span class="inline-block py-1 text-xs font-semibold" style="color: {{ z.color }}">
          {{ z.zonef }}
        </span>
      </div>
      <div class="text-right">
        <span class="inline-block text-xs text-gray-400">
          {{ z.range }}
        </span>
      </div>
    </div>
    <div class="flex h-2 mb-4 overflow-hidden text-xs rounded" style="background-color: {{ z.bg }}">
      <div style="width: {{ z.percent }}; background-color: {{ z.color }};"
        class="flex flex-col justify-center text-center whitespace-nowrap">
      </div>
    </div>
  </div>
  {% endfor %}
</section>

<script src="//cdn.jsdelivr.net/npm/chart.js@3.5.1/dist/chart.min.js"></script>
<script>
  const data = {{ activity.heart_rate_zones|safe }};
  const config = {
    type: 'doughnut',
    options: {
      plugins: {
        legend: {
            display: false,
            position: 'bottom',
        },
        tooltip: {
          callbacks: {
            label(context) {
                return ' ' + data[context.dataIndex].zonef + ': ' + data[context.dataIndex].timef;
            },
          },
        },
      },
    },
    data: {
      datasets: [{
        data: data.map(d => d.time),
        backgroundColor: data.map(c => c.color),
      }],
      labels: data.map(d => d.zonef),
    },
  };
  var ctx = document.getElementById('heart').getContext('2d');
  var chart = new Chart(ctx, config);
</script>

theme/templates/activity/_activity_map.html
{% load static %}

{% if activity.start_location %}
  {% if request.user == activity.user or not activity.hide_map %}
    <a href="{% url "activity:route" activity.id %}"
       class="overflow-hidden rounded text-link"
       title="View 3D map">
      <div style="width: 718px; height: 287px;">
        <div class="flex items-center" style="width: 718px; height: 287px;">
          <img src="{% get_media_prefix %}{{ activity.map }}" class="object-cover rounded" />
        </div>
      </div>
    </a>
  {% endif %}
{% endif %}

theme/templates/activity/detail.html
{% extends "base.html" %}

{% load heroicons %}
{% load humanize %}
{% load tz %}
{% load static %}

{% block title %}{{ activity.type }}: {{ activity.name }}{% endblock %}

{% block image %}{% if activity.start_location and not activity.hide_map %}https://{{ request.get_host }}{% get_media_prefix %}{{ activity.map }}{% endif %}{% endblock %}

{% block main %}
  <section class="flex items-center justify-start my-10 space-x-2">
    <h1 class="text-4xl font-bold">
        {{ activity.type }}: {{ activity.name }}
    </h1>
  </section>

  <section class="mb-8 space-y-2">
    <ul class="space-y-4">
      {% include "activity/_activity_detail.html" %}
    </ul>
  </section>
{% endblock %}

theme/templates/activity/edit.html
{% extends "base.html" %}

{% load heroicons %}
{% load humanize %}
{% load tz %}

{% block main %}
  <section class="flex items-center justify-start my-10 space-x-2">
    <h1 class="text-4xl font-bold">
        {{ activity.type }}: {{ activity.name }}
    </h1>
  </section>

  <section class="mb-8 space-y-2">
    <form method="post" class="px-4 py-6 mt-8 bg-white border rounded space-y-6">
        {{ form.non_field_errors }}
        <div>
            <label for="{{ form.name.id_for_label }}">Name:</label>
            {{ form.name }}
            {{ form.name.errors }}
        </div>
        <div>
            <label for="{{ form.description.id_for_label }}">Description:</label>
            {{ form.description }}
            {{ form.description.errors }}
        </div>
        {% if activity.start_location %}
        <div class="flex items-center justify-start space-x-2">
            {{ form.hide_map }}
            {{ form.hide_map.errors }}
            <label for="{{ form.hide_map.id_for_label }}">Hide the map</label>
        </div>
        <div>
            <label for="{{ form.initial_rotation.id_for_label }}">Initial 3D map rotation: (degree)</label>
            {{ form.initial_rotation }}
            {{ form.initial_rotation.errors }}
        </div>
        {% endif %}

        <div class="space-x-2">
          <input type="submit" value="Update" class="btn btn-primary">
          <a href="{% url "activity:detail" activity.id %}" class="btn btn-outline">
            Cancel
          </a>
        </div>
        {% csrf_token %}
    </form>
  </section>
{% endblock %}

theme/templates/activity/progress.html
<section class="px-4 py-6 border rounded">
  <p class="text-center">
    Your fitness progress goes here.
  </p>
</section>

theme/templates/activity/rss.html
{% load static %}

{% with obj as activity %}
  {% include "activity/_activity_desc.html" %}

  {% if activity.start_location and not activity.hide_map %}
    <img src="https://{{ request.get_host }}{% get_media_prefix %}{{ activity.map }}" />
  {% endif %}
{% endwith %}